/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Mar 12 2022
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */
#include <xc.h>
#include <stdbool.h>
#include "config.h"

#define LOGIC_HIGH 1
#define LOGIC_LOW 0
#define _XTAL_FREQ 8000000

#define DIS0 PORTAbits.RA0
#define DIS1 PORTAbits.RA1
#define DIS2 PORTAbits.RA2
#define DIS3 PORTAbits.RA3

#define and &&
#define or  ||

enum status {RUNNING, STOPPED};

int counter = 0;

const char NUMBERS[] = {0b00111111, 0b00000110,
                        0b01011011, 0b01001111,
                        0b01100110, 0b01101101,
                        0b01111101, 0b00000111,
                        0b01111111, 0b01101111};

//Print number to 7SEG displays
//pointPos > 0
void imprimir_segments(int number, bool is_decimal, char pointPos)
{   
    for (int currDisplay = 0; currDisplay < 4; ++currDisplay)
    {
        int value = number % 10;
        //If decimal NUMBERS[] or 0b10000000 (8th bit is dp bit)
        //Otherwise just print value loaded from array
        if (is_decimal)
        {
            if (currDisplay == pointPos) LATD = NUMBERS[value] | 0x80;
            else LATD = NUMBERS[value];
        } 
        else LATD = NUMBERS[value];

        switch (currDisplay)
        {
            case 0: DIS0 = LOGIC_HIGH; break;
            case 1: DIS1 = LOGIC_HIGH; break;
            case 2: DIS2 = LOGIC_HIGH; break;
            case 3: DIS3 = LOGIC_HIGH; break;
        }
    
        __delay_us(50);

        DIS0 = DIS1 = DIS2 = DIS3 = 0x0;
        number = number / 10;
    }
}

//Muestra digito "digit" por la pantalla
//"display" del set de pantallas de 7-Segmentos
void displayDigit(char display, int digit)
{
        //If decimal NUMBERS[] or 0b10000000 (8th bit is dp bit)
        //Otherwise just print value loaded from array
        LATD = NUMBERS[digit];

        switch (display)
        {
            case 0: DIS0 = LOGIC_HIGH; break;
            case 1: DIS1 = LOGIC_HIGH; break;
            case 2: DIS2 = LOGIC_HIGH; break;
            case 3: DIS3 = LOGIC_HIGH; break;
        }
    
        __delay_us(50);

        DIS0 = DIS1 = DIS2 = DIS3 = 0x0;
}

//Muestra cuatro cifras de menor peso
//de un número decimal por pantalla 
//de 7-Segmentos
void displayNumber(int number)
{
    for (int currDisplay = 0; currDisplay < 4; ++currDisplay)
    {
        int value = number % 10;
        displayDigit(currDisplay, value);
        number = number / 10;
    }
}

//increase contador according to pin_number value
void addPORTB(int *counter, char pin_number)
{
    switch(pin_number)
    {
        case 0: *counter = *counter + 1; break;
        case 1: *counter = *counter + 10; break;
        case 2: *counter = *counter + 100; break;
        case 3: *counter = *counter + 1000; break;
    }
}

//High priority interrupt service routine
void interrupt ISR_other(void)
{
    if (INTCONbits.INT0IE and INTCONbits.INT0IF)
    {
        INTCONbits.INT0IF = 0;
        INTCON3bits.INT1IE = !INTCON3bits.INT1IE;
        INTCON3bits.INT2IE = !INTCON3bits.INT2IE;
        return;
    }
}

//Low priority interrupt service routine
void interrupt low_priority ISR_low(void)
{
    if (INTCON3bits.INT1IE and INTCON3bits.INT1IF)
    {
        INTCON3bits.INT1IF = 0;
        ++counter;
        if (counter > 9999) counter = 0;
        return;
    }
    if (INTCON3bits.INT2IE and INTCON3bits.INT2IF)
    {
        INTCON3bits.INT2IF = 0;
        --counter;
        if (counter < 0) counter = 0;
        return;
    }
    
}

// setup PORTs for I/O
void config_PIC(void)
{
    ANSELA = 0b00000000; // Set pins for digital I/O
    ANSELB = 0b00000000; // Set pins for digital I/O
    ANSELC = 0b00000000; // Set pins for digital I/O
    ANSELD = 0b00000000; // Set pins for digital I/O
    ANSELE = 0b00000000; // Set pins for digital I/O

    TRISBbits.RB0 = LOGIC_HIGH; // Set pin as input
    TRISBbits.RB1 = LOGIC_HIGH; // Set pin as input
    TRISBbits.RB2 = LOGIC_HIGH; // Set pin as input
    TRISBbits.RB3 = LOGIC_HIGH; // Set pin as input

    TRISAbits.RA0 = LOGIC_LOW; // Set pin as output
    TRISAbits.RA1 = LOGIC_LOW; // Set pin as output
    TRISAbits.RA2 = LOGIC_LOW; // Set pin as output
    TRISAbits.RA3 = LOGIC_LOW; // Set pin as output

    TRISD = 0x00; // Set all pins from PORTD as output

    LATA = 0x00; //7SEG displays are turned off at start
    LATD = 0x00; //Initial 7SEG output val is 0
}

//setup interrupts for PIC18
void setupInterruptions(void)
{
    RCONbits.IPEN = 1;          //Interrupt priority enable bit
    INTCONbits.GIEH = 1;        //Global Interrupt enable bit
    INTCONbits.GIEL = 1;        //Enable low priority interrupts

    INTCON2bits.INTEDG1 = 1;    //Interrupt on INT1 rising edge  
    INTCON2bits.INTEDG2 = 1;    //Interrupt on INT2 rising edge 


    // INTO interrupt is always at the high priority because its request
    // appears in both the high-priority and the low-priority logic circuit.

    INTCON3bits.INT1IP = 0;     //External interrupt priority low INT1
    INTCON3bits.INT2IP = 0;     //External interrupt priority low INT2

    
    INTCONbits.INT0IE = 1;     //External interrupt enable INT0
    INTCON3bits.INT1IE = 0;     //External interrupt enable INT1
    INTCON3bits.INT2IE = 0;     //External interrupt enable INT2

    //INTE1/INTE2 disable at start so user can turn them on later on

    INTCONbits.INT0IF = 0;      //Clear IF flag of INT0 interrupt
    INTCON3bits.INT1IF = 0;     //Clear IF flag of INT1 interrupt
    INTCON3bits.INT2IF = 0;     //Clear IF flag of INT3 interrupt
}

//DISPLAY binary 1  if players wins the game
int winner() { return 0b00000001; }

//DISPLAY binary 2  if players loses the game
int loser() { return 0b00000010; }

//start game
void game_start(int *_game_stat) {*_game_stat = RUNNING;}

//stop game
void game_stop(int *_game_stat) {*_game_stat = STOPPED;}

void main(void)
{
    config_PIC();
    setupInterruptions();
    
    // Write your code here

    //nothing to be done in the main loop
    while (1) {displayNumber(counter);}
}